apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ndn-producer
  name: ndn-producer
spec:
  selector:
    matchLabels:
      app: ndn-producer
  serviceName: ndn-producer
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ndn-producer
    spec:
      containers:
      - env:
        - name: gateway
          value: ndn-router
        - name: monitoring_port
          value: "8081"
        - name: routes
          value: ndn-router
        image: aqual1te/ndn:producer1
        name: ndn-producer1
        ports:
        - containerPort: 8080
      restartPolicy: Always
