version: "3"

services:
  ndn-base-image:
    build: ./base
    container_name: ndnbase
  ndn-router:
    build: ./router
    container_name: ndn-router1
    hostname: ndn-router1
    ports:
      - 6363:6363
      - 8080:8080
  ndn-client:
    build: ./client
    container_name: ndn-client1
    hostname: ndn-client1
    ports:
      - 8081:8080
    depends_on:
      - ndn-router
    environment:
      - gateway=ndn-router1
