version: "3"

services:
  ndn-base-image:
    build: ./base
    container_name: ndnbase
  ndn-router:
    build: ./router
    container_name: ndn-router1
    hostname: ndn-router1
    ports:
      - 8080:8080
    environment:
      - gateway=ndn-producer
      - monitoring_port=8080
      - routes=/ndn/ark /ndn/doi /ndn/handle /ndn/urn
    depends_on:
      - ndn-base-image
  ndn-producer:
    build: ./producer
    container_name: ndn-producer1
    hostname: ndn-producer1
    ports:
      - 8081:8080
    depends_on:
      - ndn-router
    environment:
      - gateway=ndn-router1
      - monitoring_port=8081
      - routes=ndn-router1	  
  ndn-gateway:
    build: ./gateway
    container_name: ndn-gateway1
    hostname: ndn-gateway1
    ports:
      - 8082:8080
    depends_on:
      - ndn-router
      - ndn-producer
    environment:
      - gateway=ndn-router1
      - monitoring_port=8082
      - routes=ndn-router1	  
  ndn-consumer:
    build: ./consumer
    container_name: ndn-consumer1
    hostname: ndn-consumer1
    ports:
      - 8083:8080
    depends_on:
      - ndn-router
      - ndn-producer
      - ndn-gateway
    environment:
      - gateway=gateway1
      - monitoring_port=8083
      - routes=ndn-router1
