apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ndn-router
  name: ndn-router
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ndn-router
    spec:
      containers:
      - env:
        - name: monitoring_port
          value: "8080"
        - name: routes
          value: /example /os3 /uva
        image: ndn-router
        name: ndn-router1
        ports:
        - containerPort: 8080
        resources: {}
      hostname: ndn-router1
      restartPolicy: Always
status: {}
