apiVersion: v1
kind: Service
metadata:
  name: efault-subdomain # name of service
spec:
  selector:
    name: busybox # everything with this label will have these ports open
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox1 # name of the pod
  labels:
    name: busybox # has label busybox, and thus the ports of that service
spec:
  hostname: busybox-nimes # dns name of th epod
  nodeName: nimes
  subdomain: default-subdomain # name of subdomain
  containers:
  - image: busybox:1.28
    command:
      - sleep
      - "3600"
    name: busybox # name of container
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2 # name of pod
  labels:
    name: busybox # label of the pod
spec:
  hostname: busybox-mulhouse # dns name
  nodeName: mulhouse
  subdomain: default-subdomain # name of subdomain
  containers:
  - image: busybox:1.28
    command:
      - sleep
      - "3600"
    name: busybox # name of container
