apiVersion: v1
kind: Service
metadata:
  name: ndn
spec:
  ports:
  - name: monitoring
    port: 8080
    targetPort: 8080
  - name: ndn1
    port: 6363
    targetPort: 6363
  - name: ndn2
    port: 9696
    targetPort: 9696
  selector:
    name: ndn
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: ndn
    role: consumer
  name: ndn-consumer-1
spec:
  hostname: ndn-consumer-1
  nodeName: mulhouse
  subdomain: ndn
  containers:
    - image: aqual1te/ndn:consumer3
      name: ndn-consumer-1
      env:
      - name: gateway
        value: ndn-producer-1.ndn.default.svc.cluster.local
      - name: monitoring_port
        value: "8081"
      - name: routes
        value: /ndn
      - name: protocol
        value: udp
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: ndn
    role: consumer
  name: ndn-consumer-2
spec:
  hostname: ndn-consumer-2
  nodeName: nimes
  subdomain: ndn
  containers:
    - image: aqual1te/ndn:consumer3
      name: ndn-consumer1
      env:
      - name: gateway
        value: ndn-producer-1.ndn.default.svc.cluster.local
      - name: monitoring_port
        value: "8081"
      - name: routes
        value: /ndn 
      - name: protocol
        value: udp
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: ndn
    role: producer
  name: ndn-producer-1
spec:
  hostname: ndn-producer-1
  nodeName: mulhouse
  subdomain: ndn
  containers:
    - image: aqual1te/ndn:producer3
      name: ndn-producer1
      env:
      - name: gateway
        value: ndn-router
      - name: monitoring_port
        value: "8081"
      - name: routes
        value: ndn-router
      - name: protocol
        value: udp
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: ndn
    role: router
  name: ndn-router-1
spec:
  hostname: ndn-router-1
  nodeName: mulhouse
  subdomain: ndn
  containers:
    - image: aqual1te/ndn:router3
      name: ndn-router1
      env:
      - name: gateway
        value: ndn-router
      - name: monitoring_port
        value: "8081"
      - name: routes
        value: ndn-router
      - name: protocol
        value: udp
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: ndn
    role: router
  name: ndn-router-2
spec:
  hostname: ndn-router-2
  nodeName: nimes
  subdomain: ndn
  containers:
    - image: aqual1te/ndn:router3
      name: ndn-router1
      env:
      - name: gateway
        value: ndn-router
      - name: monitoring_port
        value: "8081"
      - name: routes
        value: ndn-router
      - name: protocol
        value: udp
  restartPolicy: Always
